#
# (C) COPYRIGHT 2012-2013, 2017 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# SPDX-License-Identifier: GPL-2.0
#
#

MALI_CUSTOMER_RELEASE = 1

soc_name := 7420

obj-y += /platform/exynos/gpu_integration_callbacks.o
obj-y += /platform/exynos/mali_kbase_platform.o
obj-y += /platform/exynos/gpu_notifier.o
obj-y += /platform/exynos/gpu_exynos$(soc_name).o
obj-y += /platform/exynos/gpu_control.o
obj-y += /platform/exynos/gpu_pmqos.o
obj-y += /platform/exynos/gpu_utilization.o
obj-y += /platform/exynos/gpu_dvfs_handler.o
obj-y += /platform/exynos/gpu_dvfs_api.o
obj-y += /platform/exynos/gpu_dvfs_governor.o
obj-y += /platform/exynos/gpu_perf.o
obj-y += /platform/exynos/gpu_balance.o
obj-y += /platform/exynos/gpu_job_fence_debug.o
obj-$(CONFIG_MALI_SEC_HWCNT) += /platform/exynos/gpu_hwcnt_sec.o
obj-$(CONFIG_MALI_DEBUG_SYS) += /platform/exynos/gpu_custom_interface.o
obj-$(CONFIG_CPU_THERMAL_IPA) += /platform/exynos/gpu_ipa.o
